//Even Fibonacci numbers

//Each new term in the Fibonacci sequence is generated by adding the previous 
//two terms. 

//By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not 
//exceed four million, find the sum of the even-valued terms.


function makeFibTerms(number){
    if(number <= 1){
        return 1; 
    }
    return makeFibTerms(number-1) + makeFibTerms(number-2);
}

var sum = 0;

for (var i = 1; i < 1000000; i++ ){
    var fibTerms = makeFibTerms(i);
    if (fibTerms > 4000000) {
        console.log(sum); 
        return sum;
    } 
    if(fibTerms % 2 == 0) {
        sum += fibTerms;
    }
};

//answer = 4613732


